version: '3'
services:
  py-srv:
    build:
      context: py-srv
    command: python /app/app.py
    ports:
      - 80:8050
    depends_on:
      - db-runner
    links:
      - "db:db"

  db:
    image: cockroachdb/cockroach:v19.2.4
    container_name: db
    ports:
     - "20000:26257"
     - "8000:8080"
    command: start --insecure

  db-runner:
    image: cockroachdb/cockroach:v19.2.4
    command:
      - shell
      - /usr/local/bin/init-data.sh
      - db:26257
    volumes:
     - ./db/init-data.sh:/usr/local/bin/init-data.sh:ro
     - ./db/sql:/docker-entrypoint-initdb.d
    depends_on:
     - db
    links:
     - "db:db"
